---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang}

inputs:
- name: docs
- name: version
  optional: true

caches:
- path: gopath

outputs:
- name: built-docs

params:
  ANALYTICS_ID:

run:
  path: docs/ci/build
